---
- name: validate pf9/host_id.conf
  stat:
    path: /etc/pf9/host_id.conf
  register: stat_hostid
  failed_when: stat_hostid.stat.exists == false

- name: get host_id
  shell: cat /etc/pf9/host_id.conf | grep ^host_id | cut -d = -f2 | cut -d ' ' -f2
  register: host_id

- set_fact:
    flags: ""
  when: flags is undefined

- name: INFO starting wait_for_agent_convergence
  debug: 
    msg: "running wait_for_agent_convergence.sh {{du_fqdn}} {{host_id.stdout.strip()}} {{du_token}} {{flags}}"

- name: wait for pf9-hostagent to converge
  script: "files/wait_for_agent_convergence.sh {{du_fqdn}} {{host_id.stdout.strip()}} {{du_token}} {{flags}}"
  register: waitfor_agent
