---
- include_vars: "{{ ansible_os_family|lower }}.yml"

- name: Install NTP
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ ntp_packages }}"

- name: Enable and start NTP
  service:
    name: "{{ ntp_service_name }}"
    state: started
    enabled: yes
  when: ntp_service_name is defined
