---
- name: Add execute permission to installer
  file:
    path: "/tmp/platform9-install-{{du_region}}-{{ansible_os_family|lower}}.sh"
    mode: 0755

- name: set proxy variable
  set_fact:
    proxy: "{{'--proxy='+ proxy_url if proxy_url is defined else ''}}"

- name: Check if pf9-hostagent in installed (Ubuntu)
  shell: "`which dpkg-query` -s pf9-hostagent > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: pkg_state
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_pkg_mgr == "apt"

- name: Install pf9-hostagent on Ubuntu hypervisor/containervisor
  shell: "/tmp/platform9-install-{{du_region}}-{{ansible_os_family|lower}}.sh{{proxy}} --no-ntpd --skip-os-check"
  when: pkg_state.stdout is defined and pkg_state.stdout.strip() == "not-installed"


- name: Check pf9-hostagent is installed (RedHat)
  shell: "`which rpm` -qa | grep pf9-hostagent > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: pkg_state
  when:
    - ansible_os_family == "RedHat"
    - ansible_pkg_mgr == "yum"

- name: Install pf9-hostagent on RedHat/Centos hypervisor/containervisor
  shell: "/tmp/platform9-install-{{du_region}}-{{ansible_os_family|lower}}.sh{{proxy}} --no-ntpd --skip-os-check"
  when: pkg_state.stdout is defined and pkg_state.stdout.strip() == "not-installed"
