---
- name: Download Platform9 installers
  script: files/pf9_get_hostagent.py --account_endpoint "{{du_fqdn}}" --region "{{du_region}}" --token "{{du_token}}" --platform "{{ansible_os_family|lower}}"
  args:
    chdir: /tmp
    executable: "{{ ansible_python.executable }}"
    register: agent_install
  when: proxy_url is undefined

- name: Download Platform9 installers
  script: files/pf9_get_hostagent.py --account_endpoint "{{du_fqdn}}" --region "{{du_region}}" --token "{{du_token}}" --proxy "{{proxy_url}}" --platform "{{ansible_os_family|lower}}"
  args:
    chdir: /tmp
    executable: "{{ ansible_python.executable }}"
    register: agent_install
  when: proxy_url is defined

- include: classic-packages.yml

- name: Enable and start pf9-hostagent
  service:
    name: pf9-hostagent
    state: started
    enabled: yes
