---

- name: Upgrade Repository Cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install curl, uuid-runtime, software-properties-common, logrotate
  apt:
    pkg:
    - curl
    - uuid-runtime
    - software-properties-common
    - logrotate
    state: present
